config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :forums do
      resources :comments
    end
    root 'forums#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :forum
  belongs_to :user
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :forums
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_forum
    before_action :find_comment, only: [:edit, :update, :destroy]

    def create
        @forum = Forum.find(params[:forum_id])
        @comment = @forum.comments.create(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            redirect_to forum_path(@forum)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            redirect_to forum_path(@forum)
        else 
            render 'edit'
        end
    end
    
    def destroy
      @comment.destroy
      redirect_to forum_path(@forum)
    end
        

    private
    def comment_params
        params.require(:comment).permit(:message)
    end

    def find_forum
        @forum = Forum.find(params[:forum_id])
    end

    def find_comment
        @comment = @forum.comments.find(params[:id])
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :forum_finding, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new]

    def index
        @forums = Forum.all.order("created_at DESC")
    end
    
    # def show
    #    @forum = Forum.find(params[:id])
    # end
    
    def new
        @forum = Forum.new
    end
    
    def create
        @forum = current_user.forums.build(forum_params)
        if @forum.save
            redirect_to root_path
        else 
            render 'new'
        end
    end
    
    def update
        if @forum.update(forum_params)
            redirect_to forum_path
        else 
            render 'edit'
        end
    end
    
    def destroy
      @forum.destroy
      redirect_to root_path
    end

    private
    def forum_params
        params.require(:forum).permit(:thread, :content)
    end
    
    def forum_finding
        @forum = Forum.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.message %></p>
<p><b>Posted by</b> <%= @forum.user.email %>, <%= time_ago_in_words(@forum.created_at) %> ago</p>

<% if user_signed_in? %>
  <% if @forum.user_id == current_user.id %>
    <%= link_to "Edit", edit_forum_comment_path(comment.forum, comment) %>
    <%= link_to "Delete", forum_comment_path(comment.forum, comment), 
      data: { 
        turbo_method: :delete,
        controller: "confirm", 
        action: "click->confirm#confirm", 
        confirm_message_value: "Are you sure to delete this comment?" 
      } 
    %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@forum, @forum.comments.build]) do |f| %>
<%= f.input :message, label: 'Comment' %>
<%= f.button :submit, class: "btn btn-secondary"%>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for ([@forum, @comment]) do |f| %>
<%= f.input :message, label: 'Comment' %>
<%= f.button :submit, class: "btn btn-secondary"%>
<% end %>

app/views/forums/_form.html.erb
<%= simple_form_for @forum do |f| %>
<%= f.input :thread, label: 'Thread' %>
<%= f.input :content, label: 'Content' %>
<%= f.button :submit, class: "btn btn-secondary"%>
<% end %>

app/views/forums/edit.html.erb
<h1>Thread Edition</h1>
<%= render 'form' %>

app/views/forums/index.html.erb
<div class="container">
 <div class="row justify-content-center">
    <% @forums.each do |forum| %>
      <div class="col-md-4 mb-5 d-flex justify-content-center">
         <div class="card d-flex flex-column justify-content-between text-bg-secondary p-3" style="width: 30em; height: 15em;">
             <!-- TOP: thread title -->
          <div>
            <h2 class="thread-title px-3 pt-3"><%= forum.thread %> </h2>
             </div>

          <!-- BOTTOM: button -->
            <div class="mt-auto text-center">
            <%= link_to "View Forum Thread", forum_path(forum), class: "btn btn-outline-light" %>
        </div>

        </div>
      </div>
    <% end %>
  </div>
   <div class="text-center mt-4">
<%= link_to "New Forum Thread", new_forum_path %>
  </div>
</div>

app/views/forums/new.html.erb
<h1>New Forums</h1>
<%= render 'form' %>

app/views/forums/show.html.erb
<div class="container justify-content-center" style="background-color: #8b4513;">
<div class="thread-show" style="color: white;"  >
<h2><%= @forum.thread %> </h2>
<p><b>Posted by 💌</b> <%= @forum.user.email %>, <%= time_ago_in_words(@forum.created_at) %> ago</p>
<p><%= @forum.content %> </p>

<h3>Comments:</h3>
<%= render @forum.comments %>

<h3>Reply to the thread:</h3>
<%= render 'comments/form' %>

<%= link_to "Back", root_path, class: "link-light"%>

<% if user_signed_in? %>
  <% if @forum.user_id == current_user.id %>
    <%= link_to "Edit", edit_forum_path(@forum), class: "link-light" %>
    <%= link_to "Delete", forum_path(@forum),  class: "link-light",
      data: { 
        turbo_method: :delete,
        controller: "confirm", 
        action: "click->confirm#confirm", 
        confirm_message_value: "Are you sure to delete this thread?" 
      } 
    %>
  <% end %>
<% end %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Web Forum" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" , rel: "stylesheet", integrity:"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" , crossorigin:"anonymous" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-secondary ">
        <div class="container-fluid">
            <div class="navbar-header ">
                <%= link_to "Home", root_path, class: "navbar-brand" %>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                    </li>
                    <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "nav-link" %>

                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <ul class="navbar-nav  ms-auto">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "New Forum Thread", new_forum_path, class: "navbar-right navbar-text nav-link" %>
                </li>
                <% end %>
            </ul>

        </div>
    </nav>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</body>

</html>